cxx_test(
  name = 'test',
  srcs = glob([
    '*.cpp', 
  ]),
  compiler_flags = ['-fPIC', '-pthread'],
  linker_flags = ['-pthread'],
  platform_linker_flags = [
    ('linux.*', [ '-lc++', '-lc++abi' ]), 
  ], 
  deps = [
    '//:conduit', 
    'google.gtest//:gtest', 
  ], 
)
