cxx_binary(
  name = 'squares',
  srcs = [
    'main.cpp', 
  ],
  compiler_flags = [
    '-fPIC', 
    '-pthread', 
  ],
  linker_flags = [
    '-pthread', 
  ],
  deps = [
    '//:conduit', 
  ], 
)
